import discord
from discord.ext import commands
import random

# Intents setup
intents = discord.Intents.all()
intents.members = True  # This enables the Server Members Intent
intents.message_content = True  # This enables the Message Content Intent

# Sets the prefix for the Bot to be '!' and ensures the case is not sensitive with the commands.
client = commands.Bot(command_prefix="!", intents=intents, case_insensitive=True)

# Displays message in terminal whenever bot is ready
@client.event
async def on_ready():
    print("Discord-bot kjører og er klar til bruk.")
    print("-----------------------------")

# List of intermediate to advanced Norwegian words, their English translations, and context sentences
norwegian_words = [
    ("abstrakt", "abstract", "Hans malerier er veldig abstrakte."),
    ("bevisst", "conscious/aware", "Hun var bevisst om farene."),
    ("forsvinne", "disappear", "Solen forsvant bak skyene."),
    ("nysgjerrig", "curious", "Barnet var veldig nysgjerrig på verden."),
    ("omfattende", "comprehensive", "Han ga en omfattende forklaring."),
    ("overflødig", "redundant/superfluous", "Mange av detaljene var overflødige."),
    ("sammenheng", "context/connection", "Det er viktig å forstå sammenhengen."),
    ("uvanlig", "unusual", "Det var en uvanlig situasjon."),
    ("utfordring", "challenge", "Hun tok utfordringen på strak arm."),
    ("virkelighet", "reality", "Vi må forholde oss til virkeligheten."),
    ("forutsetning", "prerequisite/condition", "En god utdannelse er en viktig forutsetning for å få en god jobb."),
    ("gjennomføre", "carry out/implement", "Vi må gjennomføre planen vår nøyaktig."),
    ("innsikt", "insight", "Hun har dyp innsikt i emnet."),
    ("beslutning", "decision", "Han tok en viktig beslutning."),
    ("omhyggelig", "meticulous", "Hun er veldig omhyggelig i arbeidet sitt."),
    ("kompleks", "complex", "Situasjonen er svært kompleks."),
    ("misforståelse", "misunderstanding", "Det var en stor misforståelse."),
    ("perspektiv", "perspective", "Han har et annet perspektiv på saken."),
    ("innflytelse", "influence", "Hun har stor innflytelse på barna."),
    ("tilstrekkelig", "sufficient", "Vi har tilstrekkelig med ressurser."),
    ("fremgangsmåte", "procedure", "Dette er den riktige fremgangsmåten."),
    ("integritet", "integrity", "Han er kjent for sin integritet."),
    ("anerkjenne", "acknowledge", "Hun anerkjenner sine feil."),
    ("innsats", "effort", "Han la ned mye innsats i prosjektet."),
    ("betydning", "significance", "Dette har stor betydning for oss."),
    ("utvikling", "development", "Teknologiens utvikling er rask."),
    ("kontroversiell", "controversial", "Det er en kontroversiell diskusjon."),
    ("strategi", "strategy", "Vi trenger en ny strategi."),
    ("tilpasning", "adaptation", "De gjennomgikk en rask tilpasning."),
    ("forsikring", "insurance", "Forsikringen dekker skadene."),
    ("forståelse", "understanding", "Vi har en felles forståelse."),
    ("identitet", "identity", "Hun har en sterk identitet."),
    ("konsekvens", "consequence", "Dette er en alvorlig konsekvens."),
    ("konsistens", "consistency", "Vi må opprettholde konsistens."),
    ("metode", "method", "Denne metoden er veldig effektiv."),
    ("mulighet", "opportunity", "Dette er en god mulighet."),
    ("oppfatning", "perception", "Hun har en annen oppfatning."),
    ("overvåke", "monitor", "Vi må overvåke situasjonen."),
    ("pålitelig", "reliable", "Dette er en pålitelig kilde."),
    ("relevans", "relevance", "Dette har stor relevans."),
    ("ressurs", "resource", "Vann er en viktig ressurs."),
    ("samarbeid", "cooperation", "Samarbeid er nøkkelen til suksess."),
    ("skape", "create", "Vi ønsker å skape noe nytt."),
    ("systematisk", "systematic", "Vi må jobbe systematisk."),
    ("tålmodighet", "patience", "Tålmodighet er viktig."),
    ("uavhengig", "independent", "Hun er en uavhengig person."),
    ("utredning", "investigation", "Utredningen pågår fortsatt."),
    ("vitenskap", "science", "Vitenskapen har gjort store fremskritt."),
    ("anvendelse", "application", "Dette har mange anvendelser."),
    ("bekreftelse", "confirmation", "Vi trenger en bekreftelse."),
    ("definisjon", "definition", "Hva er definisjonen på dette?"),
    ("entusiasme", "enthusiasm", "Han viser stor entusiasme."),
    ("forpliktelse", "commitment", "Dette er en stor forpliktelse."),
    ("aksept", "acceptance", "Aksept er første steg til forandring."),
    ("ambisjon", "ambition", "Hun har store ambisjoner."),
    ("anerkjennelse", "recognition", "Han fikk mye anerkjennelse for arbeidet sitt."),
    ("arbeidskraft", "workforce", "Vi har en dyktig arbeidskraft."),
    ("aspekt", "aspect", "Vi må vurdere alle aspekter av saken."),
    ("avtale", "agreement", "De inngikk en avtale."),
    ("bærekraftig", "sustainable", "Vi må finne bærekraftige løsninger."),
    ("bidrag", "contribution", "Han gjorde et viktig bidrag."),
    ("differensiere", "differentiate", "Det er viktig å differensiere mellom de to."),
    ("effektivitet", "efficiency", "Vi må øke effektiviteten."),
    ("etablere", "establish", "De etablerte et nytt selskap."),
    ("faglig", "professional/academic", "Hun har en faglig bakgrunn."),
    ("forbedring", "improvement", "Vi ser en betydelig forbedring."),
    ("gjennomgang", "review", "De gjorde en grundig gjennomgang."),
    ("hensyn", "consideration", "Vi må ta hensyn til alle faktorer."),
    ("kompetanse", "competence", "Hun har høy kompetanse."),
    ("konkurranse", "competition", "Konkurransen er hard."),
    ("konsekvent", "consistent", "Vi må være konsekvente i vår tilnærming."),
    ("korrigere", "correct", "Feilen ble raskt korrigert."),
    ("kreativitet", "creativity", "Kreativitet er viktig i dette yrket."),
    ("kritisk", "critical", "Hun er kritisk til forslaget."),
    ("leder", "leader", "Han er en god leder."),
    ("løsningsorientert", "solution-oriented", "Vi trenger en løsningsorientert tilnærming."),
    ("medvirkning", "participation", "Medvirkning fra alle er nødvendig."),
    ("møte", "meeting", "Vi har et viktig møte i morgen."),
    ("nødvendig", "necessary", "Det er nødvendig å ta affære."),
    ("oppfølging", "follow-up", "Vi må ha god oppfølging."),
    ("overensstemmelse", "compliance", "Dette er i overensstemmelse med reglene."),
    ("påvirkning", "influence", "Han har stor påvirkning på beslutningen."),
    ("prioritering", "priority", "Dette er vår høyeste prioritering."),
    ("produktivitet", "productivity", "Produktiviteten har økt."),
    ("resultat", "result", "Vi venter på resultatet."),
    ("samordning", "coordination", "Samordning er nøkkelen til suksess."),
    ("selvstendig", "independent", "Hun arbeider selvstendig."),
    ("stabilitet", "stability", "Vi trenger stabilitet i markedet."),
    ("tilnærming", "approach", "Dette er en god tilnærming."),
    ("tillit", "trust", "Tillit er viktig i et forhold."),
    ("tiltak", "measure", "Vi må iverksette tiltak."),
    ("tillit", "confidence", "Han har stor tillit."),
    ("utfordre", "challenge", "Vi må utfordre status quo."),
    ("utnytte", "utilize", "Vi må utnytte ressursene bedre."),
    ("vedvarende", "persistent", "Det er et vedvarende problem."),
    ("vurdering", "assessment", "Vi trenger en ny vurdering."),
    ("økonomisk", "economic", "Dette er en økonomisk beslutning."),
    ("opplysning", "information", "Vi trenger mer opplysning om saken."),
    ("forutsette", "presuppose", "Vi må forutsette noen antagelser."),
    ("implementere", "implement", "Det er på tide å implementere planen."),
    ("indikere", "indicate", "Resultatene indikerer en positiv trend."),
    ("kommunikasjon", "communication", "God kommunikasjon er nøkkelen."),
    ("medvirke", "contribute", "Alle må medvirke til løsningen."),
    ("overvåking", "monitoring", "Overvåking av systemet er nødvendig."),
    ("prosedyre", "procedure", "Dette er standard prosedyre."),
    ("referanse", "reference", "Hun ga en god referanse."),
    ("strategisk", "strategic", "Dette er en strategisk beslutning."),
    ("tilbakemelding", "feedback", "Vi setter pris på tilbakemeldingen."),
    ("utredning", "investigation", "Utredningen pågår fortsatt."),
    ("vitenskapelig", "scientific", "Dette er en vitenskapelig tilnærming."),
    ("affære", "affair", "Dette er en privat affære."),
    ("analyse", "analysis", "Vi trenger en grundig analyse."),
    ("anonym", "anonymous", "Forfatteren ønsker å være anonym."),
    ("antakelse", "assumption", "Vi jobber ut fra denne antakelsen."),
    ("avdekke", "reveal", "Undersøkelsen avdekket flere feil."),
    ("avhør", "interrogation", "Politiet gjennomførte et avhør."),
    ("avtale", "appointment", "Jeg har en avtale hos legen."),
    ("begrensning", "limitation", "Vi må jobbe innenfor disse begrensningene."),
    ("beskrive", "describe", "Kan du beskrive situasjonen?"),
    ("bestemme", "determine", "Vi må bestemme en dato."),
    ("betraktning", "consideration", "Dette må tas i betraktning."),
    ("beundre", "admire", "Jeg beundrer hans mot."),
    ("bidra", "contribute", "Alle må bidra for å lykkes."),
    ("bistand", "assistance", "Vi trenger bistand fra eksperter."),
    ("dekke", "cover", "Forsikringen dekker alle skader."),
    ("dokumentere", "document", "Vi må dokumentere resultatene."),
    ("dødelighet", "mortality", "Dødeligheten har økt."),
    ("effekt", "effect", "Dette har en stor effekt på miljøet."),
    ("egenart", "distinctiveness", "Hver kultur har sin egenart."),
    ("egenskap", "property", "Materialet har mange gode egenskaper."),
    ("eksistere", "exist", "Spøkelser eksisterer ikke."),
    ("ekspert", "expert", "Han er en ekspert på sitt felt."),
    ("enestående", "outstanding", "Hun har gjort en enestående jobb."),
    ("enighet", "agreement", "Vi kom til en enighet."),
    ("erkjenne", "recognize", "Vi må erkjenne realitetene."),
    ("erstatning", "compensation", "Hun fikk erstatning for skadene."),
    ("etterspørsel", "demand", "Etterspørselen etter produktet er stor."),
    ("evaluere", "evaluate", "Vi må evaluere resultatene."),
    ("eventuelt", "possibly", "Eventuelt kan vi møtes senere."),
    ("forbedre", "improve", "Vi må forbedre kvaliteten."),
    ("forbilde", "role model", "Han er et forbilde for mange."),
    ("forene", "unite", "De prøvde å forene de to partiene."),
    ("forhindre", "prevent", "Vi må forhindre flere ulykker."),
    ("forlate", "leave", "Hun måtte forlate møtet tidlig."),
    ("fornøyd", "satisfied", "Kunden var veldig fornøyd."),
    ("forpliktet", "obligated", "Han føler seg forpliktet til å hjelpe."),
    ("forsikre", "ensure", "Vi må forsikre oss om at alt er i orden."),
    ("forskjell", "difference", "Det er en stor forskjell."),
    ("forslag", "suggestion", "Har du et forslag?"),
    ("forsvinne", "disappear", "Hun forsvant sporløst."),
    ("fortsatt", "still", "Han er fortsatt syk."),
    ("forutsigbar", "predictable", "Resultatet var forutsigbart."),
    ("forvalte", "manage", "De forvalter store verdier."),
    ("fraråde", "discourage", "Jeg vil fraråde deg fra å gjøre det."),
    ("frihet", "freedom", "Frihet er viktig for alle."),
    ("frykt", "fear", "Hun overvant sin frykt."),
    ("fundament", "foundation", "Huset står på et solid fundament."),
    ("gjenopprette", "restore", "De prøver å gjenopprette systemet."),
    ("gjenoppta", "resume", "Vi skal gjenoppta arbeidet."),
    ("gjennomføre", "complete", "Vi må gjennomføre prosjektet."),
    ("glimt", "glimpse", "Jeg fikk et glimt av henne."),
    ("grunnlag", "basis", "Dette er grunnlaget for vår beslutning."),
    ("hensikt", "intention", "Hva er hensikten med dette?"),
    ("identifisere", "identify", "Vi må identifisere problemet."),
    ("imponere", "impress", "Hun imponerte alle med sin tale."),
    ("innvirkning", "impact", "Dette vil ha stor innvirkning."),
    ("inspirasjon", "inspiration", "Hun er en inspirasjon for mange."),
    ("intensjon", "intention", "Hans intensjon var god."),
    ("justere", "adjust", "Vi må justere planen."),
    ("kandidat", "candidate", "Han er en sterk kandidat."),
    ("kapasitet", "capacity", "Vi opererer på full kapasitet."),
    ("komme", "arrive", "De kommer snart."),
    ("kommunikere", "communicate", "Vi må kommunisere bedre."),
    ("komplett", "complete", "Prosjektet er nå komplett."),
    ("konstruktiv", "constructive", "Vi hadde en konstruktiv samtale."),
    ("kontinuerlig", "continuous", "Dette er en kontinuerlig prosess."),
    ("kreativ", "creative", "Hun er veldig kreativ."),
    ("kritikk", "criticism", "Han tåler kritikk godt."),
    ("kunnskap", "knowledge", "Kunnskap er makt."),
    ("lag", "team", "Vi jobber som et lag."),
    ("lignende", "similar", "Situasjonen er lignende."),
    ("logisk", "logical", "Dette er en logisk konklusjon."),
    ("løfte", "promise", "Han ga et løfte."),
    ("makt", "power", "Han har mye makt."),
    ("marked", "market", "Vi studerer markedet."),
    ("masse", "mass", "En stor masse folk samlet seg."),
    ("måte", "manner", "Dette er den riktige måten."),
    ("mestre", "master", "Han mestrer kunsten."),
    ("målsetting", "goal setting", "Vi har klare målsettinger."),
    ("motiv", "motive", "Hva er hans motiv?"),
    ("mulighet", "possibility", "Det er en mulighet."),
    ("nøyaktig", "accurate", "Resultatet er nøyaktig."),
    ("nødvendig", "essential", "Dette er nødvendig for suksess."),
    ("omfatte", "include", "Planen omfatter flere faser."),
    ("oppdrag", "mission", "Dette er vårt oppdrag."),
    ("oppnå", "achieve", "Vi ønsker å oppnå suksess."),
    ("overbevise", "convince", "Vi må overbevise dem."),
    ("overføre", "transfer", "Vi skal overføre dataene."),
    ("planlegge", "plan", "Vi må planlegge nøye."),
    ("påvirke", "affect", "Dette vil påvirke oss alle."),
    ("realisere", "realize", "Vi må realisere våre mål."),
    ("redegjøre", "account", "Han må redegjøre for sine handlinger."),
    ("representere", "represent", "Hun representerer selskapet."),
    ("revidere", "revise", "Vi må revidere rapporten."),
    ("samarbeide", "collaborate", "Vi skal samarbeide om prosjektet."),
    ("seier", "victory", "Seieren var vel fortjent."),
    ("skjebne", "fate", "Dette er min skjebne."),
    ("skjebnesvangert", "fatal", "Det var en skjebnesvanger feil."),
    ("skildre", "depict", "Boken skildrer livet i byen."),
    ("skjule", "hide", "Han prøvde å skjule sannheten."),
    ("spekulere", "speculate", "Vi kan bare spekulere."),
    ("stagnere", "stagnate", "Utviklingen har stagnert."),
    ("stemme", "vote", "Vi skal stemme over forslaget."),
    ("strategisk", "strategic", "Dette er en strategisk posisjon."),
    ("system", "system", "Vi må oppdatere systemet."),
    ("tillit", "trust", "Vi må bygge tillit."),
    ("tilnærming", "approach", "Dette er en praktisk tilnærming."),
    ("tilrettelegge", "facilitate", "Vi skal tilrettelegge for møtet."),
    ("utfordre", "challenge", "Han liker å utfordre seg selv."),
    ("utnytte", "exploit", "Vi må utnytte ressursene bedre."),
    ("viktig", "important", "Dette er en viktig sak."),
    ("visjon", "vision", "Han har en klar visjon."),
    ("ytelse", "performance", "Vi må forbedre vår ytelse."),
    ("anerkjennelse", "acknowledgment", "Hun fikk anerkjennelse for sitt arbeid."),
    ("avvik", "deviation", "Det var et avvik fra standarden."),
    ("bærekraft", "sustainability", "Bærekraft er viktig for fremtiden."),
    ("belønning", "reward", "Han fikk en belønning for sin innsats."),
    ("belyse", "illuminate", "Vi må belyse problemet fra flere vinkler."),
    ("berettige", "justify", "Hvordan kan du berettige denne avgjørelsen?"),
    ("bevare", "preserve", "Vi må bevare naturen."),
    ("deltakelse", "participation", "Deltakelse er frivillig."),
    ("detaljert", "detailed", "Rapporten er veldig detaljert."),
    ("diskutere", "discuss", "La oss diskutere saken."),
    ("dynamisk", "dynamic", "Hun er en dynamisk leder."),
    ("engasjement", "commitment", "Han viser stort engasjement."),
    ("erfaring", "experience", "Erfaring er viktig i denne jobben."),
    ("erkjenne", "admit", "Han måtte erkjenne sin feil."),
    ("evaluering", "evaluation", "Evalueringen er pågående."),
    ("evne", "ability", "Hun har stor evne til å lære."),
    ("fokusere", "focus", "Vi må fokusere på målet."),
    ("forbinde", "connect", "Veien forbinder de to byene."),
    ("forbruk", "consumption", "Forbruket av elektrisitet er høyt."),
    ("fordel", "advantage", "Han har en stor fordel."),
    ("forhåpning", "hope", "Vi har store forhåpninger til prosjektet."),
    ("fornøyelse", "pleasure", "Det var en fornøyelse å møte deg."),
    ("forretningsmessig", "business-related", "Dette er en forretningsmessig avgjørelse."),
    ("forsiktig", "cautious", "Vi må være forsiktige."),
    ("forsvarlig", "responsible", "Dette er en forsvarlig løsning."),
    ("forutse", "predict", "Det er vanskelig å forutse."),
    ("fundamental", "fundamental", "Dette er et fundamentalt problem."),
    ("gjensidig", "mutual", "Vi har en gjensidig forståelse."),
    ("gjenstå", "remain", "Mye arbeid gjenstår."),
    ("hensiktsmessig", "appropriate", "Dette er en hensiktsmessig løsning."),
    ("implementering", "implementation", "Implementeringen av systemet tar tid."),
    ("infrastruktur", "infrastructure", "Vi må forbedre infrastrukturen."),
    ("innledende", "initial", "Dette er den innledende fasen."),
    ("innsats", "effort", "Han gjorde en stor innsats."),
    ("kategorisere", "categorize", "Vi må kategorisere informasjonen."),
    ("kjennetegn", "characteristic", "Dette er et kjennetegn på suksess."),
    ("konsekvent", "consistent", "Han er konsekvent i sitt arbeid."),
    ("kostnad", "cost", "Kostnaden er høy."),
    ("kritisk", "critical", "Dette er en kritisk situasjon."),
    ("legitimitet", "legitimacy", "Vi må sikre legitimitet."),
    ("målbar", "measurable", "Resultatene må være målbare."),
    ("nyskapende", "innovative", "Dette er en nyskapende løsning."),
    ("opptre", "act", "Han må opptre profesjonelt."),
    ("overveie", "consider", "Vi må overveie alle alternativer."),
    ("pågående", "ongoing", "Prosjektet er pågående."),
    ("potensiell", "potential", "Dette har potensial til å lykkes."),
    ("realistisk", "realistic", "Vi må være realistiske."),
    ("reell", "actual", "Dette er en reell trussel."),
    ("tidsramme", "time frame", "Hva er tidsrammen for prosjektet?"),
    ("tilgjengelig", "available", "Ressursene er tilgjengelige."),
]
    # Add more words as needed

# Shuffle the list initially
random.shuffle(norwegian_words)
# Initialize a queue to keep track of the remaining words
word_queue = norwegian_words.copy()

# Command to provide the Norwegian word of the day, its English translation, and a context sentence
@client.command()
async def nyord(ctx):
    global word_queue
    if not word_queue:
        # If the queue is empty, reshuffle and refill it
        word_queue = norwegian_words.copy()
        random.shuffle(word_queue)
    word, translation, context_sentence = word_queue.pop()
    await ctx.send(f"Dagens norske ord er **{word}**.\nEngelsk oversettelse: **{translation}**.\nSetning: **{context_sentence}**")

# Example command to test if the bot is working
@client.command()
async def test(ctx):
    await ctx.send("Discord-bot kjører og er klar til bruk.")

# Run the bot with the token
client.run('YOUR_BOT_TOKEN')
